#' Compute the white sky albedo for an estimated kernel weight
#'
#' \code{albedo_compute} Computes the albedo values for a given kernel BRDF weights.
#'
#' @param solution A data frame of solution values, generated by gsvd_solution.  This has columns band, value, time, kernel
#'
#' @return Data frame that contains the time, band, value, and type (currently white-sky) albedo - for black-sky albedo we need solar noon
#'
#' @source \url{https://www.umb.edu/spectralmass/terra_aqua_modis/v006/mcd43a1_brdif_albedo_model_parameters_product}
#' @examples
#'
#' # To be filled in later

#' @export

albedo_compute<-function(solution_data) {
  # Coefficients for white sky albedo:
  ws_coefficient<- data.frame("0"=1,"1"=0.189184,"2"=-1.377622) %>%
    gather(key=kernel,value = coef,X0,X1,X2) %>%
    mutate(kernel=str_sub(kernel,-1))

  out_albedo <- solution_data %>%
    left_join(ws_coefficient,by=c("kernel")) %>%
    group_by(time,band) %>% summarize(value=sum(value*coef)) %>%
    mutate(type="white-sky") %>%
    ungroup()

  # For our bookkeeping for kernel values:
  # kernel 0: kIso
  # kernel 1: kVolumetric
  # kernel 2: kGeometric

  return(out_albedo)
}
